AWSTemplateFormatVersion: 2010-09-09
Description: >-
  s3-lambda-inception IAM role: Creates an IAM role that
  allows s3-lambda-inception to upload to the specified S3 bucket
Parameters:
  BucketName:
    Description: Name of an S3 bucket that s3-lambda-inception should be allowed to upload to
    Type: String
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - s3:ListBucket
            Resource: !Sub arn:aws:s3:::${BucketName}
          - Effect: Allow
            Action:
            - s3:PutObject
            Resource: !Sub arn:aws:s3:::${BucketName}/*
Outputs:
  RoleArn:
    Description: The created Role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
